In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
mat = np.load('/home/var_alpha/projects/SmartFolio/dataset/custom/industry.npy')
print(f'Shape: {mat.shape}')
print(f'Matrix:\n{mat}')

Shape: (4, 4)
Matrix:
[[1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [0. 0. 0. 1.]]
